### ISSUE TITLE
Improve documentation on MacOS X installation

### ISSUE THREAD

**Issue by ribeaud** [mixxxdj/libkeyfinder#11]
Hi.

Personally, I have no clue how to install this library on my **Mac OS X**, even though I read instructions given [here](https://github.com/mixxxdj/libKeyFinder).

I do not have **cmake** installed, should I install it? And what about a decent value for `/where/you/want/to/install/to` on **Mac**?

Thanks and have a beautiful day.
Kindest regards,

christian

**Comment by rramphal** [comment]
Hey Christian / @ribeaud,

I just managed to install `libkeyfinder` on my Mac (for the purposes of installing [`keyfinder-cli`](https://github.com/EvanPurkhiser/keyfinder-cli)). I thought I'd share what I did in case it helps you. Here's what I'd recommend you do:

1. Install [Homebrew](https://brew.sh/) by following the steps at https://brew.sh/. Homebrew is a pretty awesome package manager for MacOS that allows you to install software pretty quickly and easily.
2. Run `brew install cmake fftw catch2`. This command installs `cmake`, which you said you don't have installed, as well as `fftw` and `catch2`, the two dependencies listed in `libkeyfinder`'s documentation.
3. Clone repo and `cd` into it.
5. Run the following commands:

```
cmake -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -S . -B build

cmake --build build --parallel $(sysctl -n hw.logicalcpu)

cmake --install build
```

Some notes about the commands above:

* It is convention to use `/usr/local` for shared dynamic libraries on MacOS, although some warn that it might conflict with Homebrew (I have not personally run into this problem).
* We also use the `sysctl -n hw.logicalcpu` command to automatically find the number of logical cores you have available on your machine.
* I suggested you include `-DBUILD_TESTING=OFF` in the first command because it doesn't seem like you're installing this library to develop against; rather, to consume. If you were developing against it, the tests would be useful. However, if you're just using the library like I am, you can save a tiny amount of time haha!

Hopefully that helps! Let me know if it doesn't work for you.

**Comment by ribeaud** [comment]
Hey Ravi / @rramphal,

This was really useful. Thanks a million! It worked like a charm.
So maybe we should put this information in a more prominent place for the next ones?
Wishing you a great Sunday.
Kindest regards,

christian

**Comment by rramphal** [comment]
Glad to hear it! I'll open a PR now.

Have a great Sunday!
