### ISSUE TITLE
Difference in libkeyfinder output from KeyFinder?

### ISSUE THREAD

**Issue by turian** [mixxxdj/libkeyfinder#33]
This [Cm audio](https://github.com/vincentriemer/docker-keyfinder-cli/raw/refs/heads/master/test-files/Cm.mp3) is recognized as Cm in KeyFinder, but libkeyfinder through the keyfinder-cli reports the key as Gm. I've used both 2.2.8 of libkeyfinder AND the latest main.

Why?

**Comment by daschuer** [comment]
In Mixxx, the track is detected as Cm with Keyfinder and Queen Mary 

QM reports this 
debug [AnalyIn Mixxx, the track is detected as Cm with Keyfinder and Queen Mary 

QM reports this 
Key Histogram
1 : "C" 90.105
2 : "D♭" 2.22912
3 : "D" 3.71
4 : "E♭" 29.7215
6 : "F" 21.5481
9 : "A♭" 17.0899
11 : "B♭" 2.22912
13 : "Cm" 90.6507
14 : "C♯m" 2.22912
15 : "Dm" 1.48608
18 : "Fm" 23.0342
20 : "Gm" 0.743039

So you see the track contains also some Gm. I have tested it and turns out that the Gm is the first second of the track. Did you analyze the whole track when using the libeyfinder?

**Comment by turian** [comment]
Hmm strange, I'm no longer able figure out how to replicate this bug.

And https://github.com/vincentriemer/docker-keyfinder-cli worked just fine:

```
% docker run --rm -it -v $(pwd):/target -w /target vincentriemer/docker-keyfinder-cli:latest  Cm.mp3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Cm
```
